#!/usr/bin/env node
/**
 * compile-content.mjs — validate + emit authored JSON content.
 *
 * Reads config/raw/constellations/*.json, validates each file
 * against a Zod schema, and emits a single typed TS module at
 * config/compiled/content.ts. Importing consumers see the table as
 * a readonly array of typed records.
 *
 * Runs as a `prebuild` / `predev` / `pretypecheck` / `pretest:*`
 * step so authored content edits are reflected in the running app
 * without a manual build.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const rawRoot = join(repoRoot, "config/raw");
const compiledRoot = join(repoRoot, "config/compiled");

const PointSchema = z.object({
  id: z.string().min(1),
  x: z.number().min(0).max(100),
  y: z.number().min(0).max(100),
});

const ConnectionSchema = z.object({
  from: z.string().min(1),
  to: z.string().min(1),
});

const ConstellationSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  difficulty: z.number().int().min(1).max(10),
  requiredEnergy: z.number().int().positive(),
  points: z.array(PointSchema).min(3),
  connections: z.array(ConnectionSchema).min(1),
});

function loadDir(dir, schema, kind) {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  const out = [];
  for (const file of files) {
    const full = join(dir, file);
    const raw = JSON.parse(readFileSync(full, "utf8"));
    const parsed = schema.safeParse(raw);
    if (!parsed.success) {
      console.error(`[compile-content] ${kind} file ${file} failed validation:`);
      console.error(parsed.error.issues);
      process.exit(1);
    }
    out.push(parsed.data);
  }
  return out;
}

const constellations = loadDir(
  join(rawRoot, "constellations"),
  ConstellationSchema,
  "constellation",
);

// Cross-file invariant: every `connections.from` and `connections.to`
// must reference a `points.id` within the same constellation.
// Schema-level refinement would fire per-file, but this loop gives a
// clearer error trail with the offending constellation id.
for (const pattern of constellations) {
  const ids = new Set(pattern.points.map((p) => p.id));
  for (const edge of pattern.connections) {
    if (!ids.has(edge.from) || !ids.has(edge.to)) {
      console.error(
        `[compile-content] constellation "${pattern.id}" has edge ${edge.from}→${edge.to} referencing unknown point`,
      );
      process.exit(1);
    }
  }
}

// Sort by difficulty so `getConstellationForLevel(level)` can index
// directly. Authored file order is still respected for
// same-difficulty buckets via the stable Array#sort Node uses.
constellations.sort((a, b) => a.difficulty - b.difficulty);

mkdirSync(compiledRoot, { recursive: true });
const body = `// Generated by scripts/compile-content.mjs. Do not edit by hand.
// Source of truth: config/raw/constellations/*.json.

export const COMPILED_CONSTELLATIONS = ${JSON.stringify(constellations, null, 2)} as const;
`;
writeFileSync(join(compiledRoot, "content.ts"), body);
console.log(
  `[compile-content] wrote content.ts: ${constellations.length} constellations`,
);
